#!/usr/bin/env ruby

require 'shellwords'
require 'net/https'
require 'json'

begin
  require 'pleasant_lawyer'
rescue LoadError
end

def set_git_branch_description(branch, message)
  `git config --local --unset branch.#{Shellwords.shellescape branch}.description`
  `git config --local --add branch.#{Shellwords.shellescape branch}.description #{Shellwords.shellescape message}`
end

def get_git_branch_description(branch)
  `git config --local branch.#{Shellwords.shellescape branch}.description`.chomp
end

def get_beetil_title(number)
  api_token = File.read("#{File.expand_path("~")}/.service_desk_api_token").chomp

  $stderr.puts "Retrieving title for ##{number} from Service Desk..."

  uri = URI.parse("https://deskapi.gotoassist.com/v1/beetils/#{number}.json")

  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = true
  http.verify_mode = OpenSSL::SSL::VERIFY_NONE

  req = Net::HTTP::Get.new(uri)
  req.basic_auth "x", api_token

  res = http.request(req)

  if res.code == "302"
    uri = URI.parse(res["location"])
    req = Net::HTTP::Get.new(uri)
    req.basic_auth "x", api_token

    res = http.request(req)
    if res.code == "200"
      data = JSON.parse(res.body)
      data["result"].values.first["title"] if data["status"] == "Success"
    end
  end
end

def handle_feature_branch(branch, number)
  desc = get_git_branch_description(branch)
  if desc.empty? && desc = get_beetil_title(number)
    if defined?(PleasantLawyer)
      desc = %("#{PleasantLawyer.number_to_words(number.to_i).join(" ")}" #{desc})
    end
    set_git_branch_description branch, desc
  end
  desc.chomp! if desc

  $stderr.puts "\033[0;32m##{number} \033[0;36m#{desc}\033[0m"
end

def pleasant_lawyer_lookup(branch)
  if defined?(PleasantLawyer)
    number = PleasantLawyer.convert branch.gsub(/[_-]/, ' ')
    number unless number.zero?
  end
end

previous_head, new_head, branch_checkout_flag = ARGV

if branch_checkout_flag == "1"
  branch = File.read("#{File.dirname(__FILE__)}/../HEAD").chomp.split("/").last

  (matches = branch.match(/^b(\d+)$/)) && number = matches[1]
  number ||= pleasant_lawyer_lookup(branch)

  handle_feature_branch branch, number if number
end
